import 'package:flutter/material.dart';

class ColorsSchemeManager {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF01B7F1),
    onPrimary: Color(0xFF005773),
    surface: Color(0xFFFFFFFF),
    onSurfaceVariant: Color(0xFFA1A1A1),
    onSurface: Color(0xFF1E1E1E),
    primaryContainer: Color(0xFFEDFBFF),
    outlineVariant: Color(0xFF1B6180),
    shadow: Color(0xFF000000),
    surfaceContainerHighest: Color(0xFFF5F5F5),

    secondary: Color(0xFF3FD6A6),
    onSecondary: Color(0xFFFFFFFF),
    error: Color(0xFFFF0000),
    onError: Color(0xFFFFFFFF),
    onPrimaryContainer: Color(0xFF3C0D72),
    secondaryContainer: Color(0xFFB3EFDC),
    onSecondaryContainer: Color(0xFF145C45),
    tertiary: Color(0xFFFF4499),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFB3D5),
    onTertiaryContainer: Color(0xFF800039),
    errorContainer: Color(0xFFFF9999),
    onErrorContainer: Color(0xFF660000),
    outline: Color(0xFF8292A1),

    inverseSurface: Color(0xFF353238),
    onInverseSurface: Color(0xFFFFFFFF),
    inversePrimary: Color(0xFF4B108D),

    surfaceTint: Color(0xFF003f7a),

    scrim: Color(0xFF000000),
    primaryFixed: Color(0xFFFFFFFF),
  );
  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF3FD6A6),
    onPrimary: Color(0xFFFFFFFF),
    secondary: Color(0xFF4B108D),
    onSecondary: Color(0xFFFFFFFF),
    error: Color(0xFFFF0000),
    onError: Color(0xFFFFFFFF),
    surface: Color(0xFF0F0016),
    onSurface: Color(0xFFEEF0F2),
    primaryContainer: Color(0xFFB3EFDC),
    onPrimaryContainer: Color(0xFF27B588),
    secondaryContainer: Color(0xFFB47FF0),
    onSecondaryContainer: Color(0xFF1D0637),
    tertiary: Color(0xFFFF6BAE),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFF800039),
    onTertiaryContainer: Color(0xFFFFDBEB),
    errorContainer: Color(0xFF660000),
    onErrorContainer: Color(0xFFFFCCCC),
    outline: Color(0xFFBCC5CD),
    surfaceContainerHighest: Color(0xFF190024),
    onSurfaceVariant: Color(0xFFCBD1D8),
    inverseSurface: Color(0xFFFFFFFF),
    onInverseSurface: Color(0xFF353238),
    inversePrimary: Color(0xFF3FD6A6),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF003f7a),
    outlineVariant: Color(0xFFAAB5BF),
    scrim: Color(0xFF000000),
    primaryFixed: Color(0xFF14002B),
  );
}
