
default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution"
  lane :firebase_distribution do
      sh "flutter clean"
      sh "flutter build apk --release --no-tree-shake-icons"
        firebase_app_distribution(
          app: "1:1023418097581:android:c5b0a5d5aadd972778cb24",
          firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
          android_artifact_type: "APK",
          android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
          testers: "abdelrahman.hosni.20@gmail.com",
          release_notes: "Add FIREBASE_CLI_TOKEN to Github actions secrets"
        )
  end
end
