name: Android Fastlane Firebase Distribution

on:
  push:
    branches:
      - master

jobs:
  firebase_distribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Repo Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Android SDK Command-line Tools
        run: |
          sudo mkdir -p /usr/local/lib/android
          sudo curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          sudo unzip commandlinetools.zip -d /usr/local/lib/android/cmdline-tools
          sudo mv /usr/local/lib/android/cmdline-tools/cmdline-tools /usr/local/lib/android/cmdline-tools/latest
          export ANDROID_HOME=/usr/local/lib/android
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager --install "ndk;29.0.13113456"

      - name: Set Environment Paths
        run: |
          echo "ANDROID_HOME=/usr/local/lib/android" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/local/lib/android/cmdline-tools/latest/bin" >> $GITHUB_ENV

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4
          bundler-cache: true
          working-directory: android

      - name: Run Fastlane
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: bundle exec fastlane android firebase_distribution
        working-directory: android
