name: Android Fastlane Firebase Distribution

on:
  push:
    branches:
      - master
jobs:
  firebase_distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout My Repo Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Add Linux platform to Gemfile.lock
        run: bundle lock --add-platform x86_64-linux
        working-directory: android

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4
          bundler-cache: true
          working-directory: android

      - name: Add Linux platform to Gemfile.lock
        run: bundle lock --add-platform x86_64-linux
        working-directory: android


      - name: Run Fastlane
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: bundle exec fastlane android docdoc_distribution
        working-directory: android